[general]
live_config_reload = true

[window]
dynamic_title = true
dimensions = { columns = 140, lines = 70 }

[font]
normal = { family = "Berkeley Mono", style = "Bold" }
size = 10

[colors.primary]
background = '#000000'
foreground = '#ffffff'

[colors.cursor]
text    = '#000000'
cursor  = '#ffffff'

[colors.normal]
black   = '#0e1415'
red     = '#e25d56'
green   = '#73ca50'
yellow  = '#e9bf57'
blue    = '#4a88e4'
magenta = '#915caf'
cyan    = '#23acdd'
white   = '#f0f0f0'

[colors.bright]
black   = '#777777'
red     = '#f36868'
green   = '#88db3f'
yellow  = '#f0bf7a'
blue    = '#6f8fdb'
magenta = '#e987e9'
cyan    = '#4ac9e2'
white   = '#ffffff'
